### ISSUE TITLE
Failed to download and validate the job-settings.json file

### ISSUE THREAD

**Issue by realvikas** [awslabs/video-on-demand-on-aws-foundations#2]
Currently `job-submit` lambda expects a `<uploaded_video>/job-settings.json` file. But the solution uploads a default `job-settings.json` inside the `assets01` directory.

This is the error that I am getting
```
{
  "Details": "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=/aws/lambda/vod-jobSubmitB391E42F-1O4CG56DZQQ8Z",
  "Error": {
    "Message": "Failed to download and validate the job-settings.json file. Please check its contents and location. Details  on using custom settings: https://github.com/awslabs/video-on-demand-on-aws-foundations",
    "Error": "AccessDenied: Access Denied"
  }
}
```

**Comment by group-a-studio** [comment]
@realvikas Did you find a solution to this? I'm having the same problem today.

**Comment by group-a-studio** [comment]
Videos have to be uploaded into a subdirectory of the SourceBucket that contains the job-settings.json file. This was not how the bucket was set up after implementing the Foundations project. Not sure if something has changed since this project was created. But creating a folder, uploading the job-settings.json file to it, and then uploading any videos into that directory works for me. The job will complete and you'll get the expected Job Complete email.

**Comment by morjoan** [comment]
Hello there, Appendix A of the Implementation Guide what to do if you'd like to use different folders for you jobs. 
https://docs.aws.amazon.com/solutions/latest/video-on-demand-on-aws-foundations/appendix-a.html
Hope this helps.
